image: docker
services:
  - docker:dind
stages:
  - build

build-job:
  stage: build
  before_script:
    - apk add --no-cache docker-compose
  script:
    - echo "Building docker images"
    - docker build -t frontend -f ./frontend/Dockerfile ./frontend/ 
    - docker build -t backend -f ./backend/Dockerfile ./backend/ 
    - echo "Building complete."